---

- name: verify pip installation
  include: install-pip.yml

- name: Make temporary bdocker directory in /opt
  file: 
     path: /opt/bdocker
     owner: root
     group: root
     mode: 0755
     state: directory
  
- name: Write configuration file
  template: 
     src: templates/configure_bdocker.cfg.j2
     dest: /etc/configure_bdocker.cfg
     backup: "{{ backup_conf_files }}"
     owner: root
     group: root
     mode: 0644
