---

- name: verify pip installation
  include: install-pip.yml

- name: get bdocker from github
  git:
    repo: https://github.com/indigo-dc/bdocker.git
    dest: /opt/bdocker
    version: master
  
- name: Write configuration file
  template: 
     src: templates/configure_bdocker.cfg.j2
     dest: /etc/configure_bdocker.cfg
     backup: "{{ backup_conf_files }}"
     owner: root
     group: root
     mode: 0644
